<<<<<<< HEAD
# Generated by Django 3.0.2 on 2020-01-17 03:10
=======
# Generated by Django 3.0.2 on 2020-01-23 21:27
>>>>>>> e502bd3260fc90b3e1fe9823154527611083423d

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('title', models.CharField(default='DEFAULT TITLE', max_length=50)),
                ('description', models.CharField(default='DEFAULT DESCRIPTION', max_length=500)),
                ('n_to', models.IntegerField(default=0)),
                ('s_to', models.IntegerField(default=0)),
                ('e_to', models.IntegerField(default=0)),
                ('w_to', models.IntegerField(default=0)),
=======
                ('title', models.IntegerField(default=0)),
                ('n_to', models.IntegerField(default=-1)),
                ('s_to', models.IntegerField(default=-1)),
                ('e_to', models.IntegerField(default=-1)),
                ('w_to', models.IntegerField(default=-1)),
                ('x', models.IntegerField(default=-1)),
                ('y', models.IntegerField(default=-1)),
>>>>>>> e502bd3260fc90b3e1fe9823154527611083423d
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentRoom', models.IntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
