# Generated by Django 3.0.2 on 2020-01-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.IntegerField(default=0),
        ),
    ]
