# Generated by Django 3.0.2 on 2020-01-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.AddField(
            model_name='room',
            name='x',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='room',
            name='y',
            field=models.IntegerField(default=-1),
        ),
    ]
